### ISSUE TITLE
Question list sections do not expand or finish loading

### ISSUE THREAD

**Issue by njscheffler** [Siyavula/monassis-issues#1]
As per Neels's request, submitting the following info:

The sections in the list of available templates (found at @@practice/question-list) often take a very long time to expand, or do not load at all.  This behaviour is presumably more prevalent for those sections with more templates (or more complex templates?), or if you attempt to expand more than one section at a time.

No specific error message is displayed.

**Comment by njscheffler** [comment]
Possibility that Neel's experience was aggravated by reduced connectivity as the result of load-shedding today.

**Comment by njscheffler** [comment]
Vastly improved by the fix Carl made to the way the database was being indexed, which was slowing everything down drastically.

**Comment by cscheffler** [comment]
Closing this issue, since the generating question lists now seems to be fast enough.
