### ISSUE TITLE
Discrepency between email addresses stored by EMAS and Monassis

### ISSUE THREAD

**Issue by njscheffler** [Siyavula/monassis-issues#3]
Neels reported some trouble submitting an error report from his account.  Here is the behaviour he described and my observations:

1) Neels has an email address saved with his account.  He checked this under his account "preferences" on EMAS.
2) Despite this, when he tried to report an error in IP, he was told he did not have an email address stored with his account and was prompted to capture and save one.
3) He tried to save his neels@siyavula.com address and was told it was not valid.

I was able to replicate all of this.

It seems that email addresses captured in the EMAS database at registration are not copied across to the Monassis database.

It seems that one can add one's email, post original sign up, to the EMAS database by adjusting your preferences, but again, this email address is not then also copied into the Monassis database.

Any siyavula email address is declared invalid, but my personal email address (@gmail.com) was accepted.

**Comment by cscheffler** [comment]
This is a feature (and not a bug) and it affects siyavula.com addresses only. The system specifically does not accept any email address
- at siyavula.com, or
- at mxit.com, or
- at S000.trial.co.za (where any 3-digit number after the S).

Any other well-formed email address is valid.

The reason for this is that Carine (and perhaps others, but I don't think so) used to use her email address for a whole lot of users. This is meant to encourage any user who still has a Siyavula email listed to supply an alternative address.

**Comment by njscheffler** [comment]
That makes perfect sense and guessed that there was probably good reason for not accepting siyavula addresses.  

What about the first part of the issue (perhaps I should have reported them separately)?  

Are you saying that having the email address (in addition to usernames and real names) added to the Monassis database is not a current feature?

**Comment by cscheffler** [comment]
You're right, this was a problem. The emails was checked and updated was different from (followed a different process to) the way in which names were checked and updated in Monassis from EMAS. I consolidated them, so that names and emails get updated at the same time.

This should resolve any remaining issues.

**Comment by njscheffler** [comment]
Thank you.

I don't think that accepting siyavula email addresses is a feature worth worrying about.  I will simply make sure S&M knows.

Therefore closing this now.
