### ISSUE TITLE
Roedean School class and learners lists missing

### ISSUE THREAD

**Issue by JessicaJaneEllis** [Siyavula/monassis-issues#5]
http://www.everythingmaths.co.za/@@practice/admin/school-overview/cce1bc2f73674d74859785071a45b792 - Chrome browser

I was merging learner accounts for class Gr 12 LK Science 1203.  When completed and page refreshed the class and learner list no longer appeared.

Checked other schools and the problem seems specific to Roedean School.  The lists were also missing when logged in on other admin accounts including a Firefox browser.

I have logged out and logged back in again and the lists are still missing.

**Comment by cscheffler** [comment]
This is fixed now.

The problem was that the school expiry date cache was not recalculated after a user merge. This cause the school overview page to be missing some user ids.
