### ISSUE TITLE
Users missing from account merge search

### ISSUE THREAD

**Issue by njscheffler** [Siyavula/monassis-issues#6]
Search for user's accounts on http://emas.siyavula.com/@@usergroup-userprefs using user's email address returns two results.  Both of the accounts returned are active and set to expire on the same day.  However, searching for both of these usernames at http://everythingmaths.co.za/@@practice/admin/user-merge results in one of them being "Not found".

Strikes me as odd. Perhaps this is related to the merge search not always returning as many accounts for potential merging as expected?

User's details in this case:
Real name: Aliziwe Mdaka
Email address: aliziwe.mdaka@gmail.com
Username 1: Amdaka (this is the one that comes up "Not found")
Username 2: mdashkacwesh

**Comment by cscheffler** [comment]
@nglenday Users will show up in the user merge only if they appear in the _Monassis_ database (and not the EMAS database). The main reason why someone might appear in EMAS but not Monassis, is that they registered an account on EMAS, but never tried to access IP using that account. Their username gets added to the Monassis database on the first occasion that they access IP.

**Comment by njscheffler** [comment]
Ok cool. I knew there was a discrepancy between Monassis and EMAS
databases, but not why. This clears up a lot. Thank you. I will pass this
info on to S&M.
