### ISSUE TITLE
Urgent: Teacher dashboard taking upwards of 1 min 30 secs to load 

### ISSUE THREAD

**Issue by njscheffler** [Siyavula/monassis-issues#8]
Several teachers have reported to Will that the teacher dashboard is taking a very long time to generate.  He assumed this was due to connectivity issues, but has now replicated this behaviour himself and so have I here in Cape Town.

I observed that it seems to get stuck in step 1 of the process (Getting started...) for well over a minute at least (I timed it several times) and then goes through steps 2 and 3 very quickly.

I have marked this urgent because it is somewhat inhibiting Will's sales efforts in KZN.

**Comment by cscheffler** [comment]
@nglenday Can you please test again and report back whether it is better now. I think I fixed the problem, but would like to be sure.

**Comment by njscheffler** [comment]
@cscheffler  - Tested.  Yup.  It is now loading in approx. 7 seconds.  Thank you.
